# Use node 10
FROM node:10

# set the working dir
WORKDIR /app

# Set the package files first, so they can be cached
COPY client/package*.json ./

# install npm dependencies, should be cached
RUN npm install

# copy all files. The src folder is not necessary, becuase it is mounted, but all other files
# like the angular.json must be copied to the image
COPY client/ ./

# start the angular client
CMD npm start