FROM cypress/base:16.13.0

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm ci

COPY ./cypress.config.js .
COPY ./resource-config.js .
COPY ./cypress .

CMD ["npm", "run", "cypress:run"]
